language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

script:
  - mkdir -p build/logs
  - ./vendor/bin/parallel-lint src test
  - ./vendor/bin/phpunit --coverage-text

after_script:
  - php vendor/bin/coveralls
